name: Home Grown San Francisco
favicon: null
layout_spectrum: 0.679117884254083
typography_spectrum: 0.43713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#111520'
    - '#8dbdf5'
    - '#373e46'
    - '#7294a7'
  brandStrength: 0.4444054167252034
  lightness: 0.5663815061561763
  saturation: 0.8767229896038771
  rhythmicContrast: 0.21879710908979177
purpose: []
